#!/bin/bash

# Configures automatic login for the primary user on tty1.

# Exit immediately if a command exits with a non-zero status.
set -e
# Treat unset variables as an error when substituting.
# set -u # Disable temporarily for grep/cut
# Ensure pipeline failures are caught.
set -o pipefail

ENV_FILE="/boot/firmware/.env" # Path to the config file on the Pi's boot partition
LOG_FILE="/var/log/setup_autologin.log" # Specific log for this script

# --- Logging ---
exec > >(tee -a "$LOG_FILE") 2>&1

log() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') INFO (setup_autologin.sh): $1"
}

warn() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') WARN (setup_autologin.sh): $1" >&2
}

error() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') ERROR (setup_autologin.sh): $1" >&2
  exit 1
}

# --- Check Prerequisites ---
if [[ ! -f "$ENV_FILE" ]]; then
  error "Environment file '$ENV_FILE' not found."
fi

# --- Read Configuration ---
SET_USERNAME=$(grep '^SET_USERNAME=' "$ENV_FILE" | cut -d '=' -f2- | sed -e 's/^"//' -e 's/"$//')
# Re-enable set -u if desired
# set -u

# --- Validate Configuration ---
if [[ -z "$SET_USERNAME" ]]; then
    error "Required variable SET_USERNAME not set or empty in $ENV_FILE."
fi

# Check if user exists
if ! id -u "$SET_USERNAME" &>/dev/null; then
    error "User '$SET_USERNAME' specified for autologin does not exist."
fi

# --- Configure Autologin ---
log "Configuring autologin for user '$SET_USERNAME' on tty1..."

SERVICE_OVERRIDE_DIR="/etc/systemd/system/getty@tty1.service.d"
SERVICE_OVERRIDE_FILE="${SERVICE_OVERRIDE_DIR}/autologin.conf"

# Create the override directory if it doesn't exist
mkdir -p "$SERVICE_OVERRIDE_DIR" || error "Failed to create systemd override directory."

# Create the override configuration file
cat << EOF > "$SERVICE_OVERRIDE_FILE"
# Generated by setup_autologin.sh for automatic console login
[Service]
# Clear default ExecStart
ExecStart=
# Add new ExecStart with autologin parameter
ExecStart=-/sbin/agetty --autologin $SET_USERNAME --noclear %I \$TERM
EOF

if [[ $? -ne 0 ]]; then
    error "Failed to write systemd override file: $SERVICE_OVERRIDE_FILE"
fi

log "Systemd override file created."
log "Reloading systemd daemon to apply changes..."
systemctl daemon-reload || warn "systemctl daemon-reload failed. Changes should apply on next boot."

log "Autologin setup completed successfully for user '$SET_USERNAME'."

exit 0